# Core
CONFIG_ZBUS=y
CONFIG_ZBUS_CHANNEL_NAME=y
CONFIG_SHELL=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Console (UART via USB-serial)
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y

# GPIO (LED built-in — feedback visual no M1)
CONFIG_GPIO=y

# Stacks
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# Shell — edicao de linha (backspace/setas) via VT100
CONFIG_SHELL_VT100_COMMANDS=y
